//
//  CovenantNotification.h
//  reader
//
//  Created by Ram Mohan on 26/12/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

extern NSString *COVNOTIFICATION_SIGNUP;
extern NSString *COVNOTIFICATION_SIGNUP_RESULT_OK;
extern NSString *COVNOTIFICATION_SIGNUP_RESULT_FAILED;

extern NSString *COVNOTIFICATION_SIGNIN;
extern NSString *COVNOTIFICATION_SIGNIN_RESULT_OK;
extern NSString *COVNOTIFICATION_SIGNIN_RESULT_FAILED;

extern NSString *COVNOTIFICATION_SIGNOUT;
extern NSString *COVNOTIFICATION_SIGNOUT_RESULT_OK;
extern NSString *COVNOTIFICATION_SIGNOUT_RESULT_FAILED;

extern NSString *COVNOTIFICATION_ACCOUNT_ACTIVATE;
extern NSString *COVNOTIFICATION_ACCOUNT_ACTIVATE_RESULT_OK;
extern NSString *COVNOTIFICATION_ACCOUNT_ACTIVATE_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_ACCOUNT_INFO;
extern NSString *COVNOTIFICATION_GET_ACCOUNT_INFO_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_ACCOUNT_INFO_RESULT_FAILED;

extern NSString *COVNOTIFICATION_UPDATE_ACCOUNT_INFO;
extern NSString *COVNOTIFICATION_UPDATE_ACCOUNT_INFO_RESULT_OK;
extern NSString *COVNOTIFICATION_UPDATE_ACCOUNT_INFO_RESULT_FAILED;

extern NSString *COVNOTIFICATION_CHANGE_PASSWORD;
extern NSString *COVNOTIFICATION_CHANGE_PASSWORD_RESULT_OK;
extern NSString *COVNOTIFICATION_CHANGE_PASSWORD_RESULT_FAILED;

extern NSString *COVNOTIFICATION_RESET_PASSWORD;
extern NSString *COVNOTIFICATION_CHANGE_PASSWORD_RESULT_OK;
extern NSString *COVNOTIFICATION_CHANGE_PASSWORD_RESULT_FAILED;

extern NSString *COVNOTIFICATION_UPDATE_DEVICE_NAME;
extern NSString *COVNOTIFICATION_UPDATE_DEVICE_NAME_RESULT_OK;
extern NSString *COVNOTIFICATION_UPDATE_DEVICE_NAME_RESULT_FAILED;

extern NSString *COVNOTIFICATION_UNLINK_DEVICE;
extern NSString *COVNOTIFICATION_UNLINK_DEVICE_RESULT_OK;
extern NSString *COVNOTIFICATION_UNLINK_DEVICE_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_CATALOGUE;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_CATALOGUE_QUICK_BOOKS;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_QUICK_BOOKS_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_QUICK_BOOKS_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_CATALOGUE_BOOKS;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_BOOKS_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_BOOKS_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_CATALOGUE_SEARCH;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_SEARCH_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_CATALOGUE_SEARCH_RESULT_FAILED;

extern NSString *COVNOTIFICATION_BOOK_PURCHASED;
extern NSString *COVNOTIFICATION_BOOK_PURCHASED_RESULT_OK;
extern NSString *COVNOTIFICATION_BOOK_PURCHASED_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_TRANSACTION_HISTORY;
extern NSString *COVNOTIFICATION_GET_TRANSACTION_HISTORY_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_TRANSACTION_HISTORY_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_MY_BOOKS;
extern NSString *COVNOTIFICATION_GET_MY_BOOKS_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_MY_BOOKS_RESULT_FAILED;

extern NSString *COVNOTIFICATION_DOWNLOAD_BOOK;
extern NSString *COVNOTIFICATION_DOWNLOAD_BOOK_RESULT_OK;
extern NSString *COVNOTIFICATION_DOWNLOAD_BOOK_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_BOOK_DETAILS;
extern NSString *COVNOTIFICATION_GET_BOOK_DETAILS_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_BOOK_DETAILS_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_BOOKS_SUMMARY;
extern NSString *COVNOTIFICATION_GET_BOOKS_SUMMARY_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_BOOKS_SUMMARY_RESULT_FAILED;

extern NSString *COVNOTIFICATION_LIKE_BOOK;
extern NSString *COVNOTIFICATION_LIKE_BOOK_RESULT_OK;
extern NSString *COVNOTIFICATION_LIKE_BOOK_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_MY_LIKES;
extern NSString *COVNOTIFICATION_GET_MY_LIKES_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_MY_LIKES_RESULT_FAILED;

extern NSString *COVNOTIFICATION_UNLIKE_BOOK;
extern NSString *COVNOTIFICATION_UNLIKE_BOOK_RESULT_OK;
extern NSString *COVNOTIFICATION_UNLIKE_BOOK_RESULT_FAILED;

extern NSString *COVNOTIFICATION_GET_MY_WISHLIST;
extern NSString *COVNOTIFICATION_GET_MY_WISHLIST_RESULT_OK;
extern NSString *COVNOTIFICATION_GET_MY_WISHLIST_RESULT_FAILED;

extern NSString *COVNOTIFICATION_ADD_TO_WISHLIST;
extern NSString *COVNOTIFICATION_ADD_TO_WISHLIST_RESULT_OK;
extern NSString *COVNOTIFICATION_ADD_TO_WISHLIST_RESULT_FAILED;

extern NSString *COVNOTIFICATION_REMOVE_FROM_WISHLIST;
extern NSString *COVNOTIFICATION_REMOVE_FROM_WISHLIST_RESULT_OK;
extern NSString *COVNOTIFICATION_REMOVE_FROM_WISHLIST_RESULT_FAILED;

@interface CovenantNotification : NSObject

@end
